apiVersion: v1
kind: Service
metadata:
  name: report-service  # 이상한 문자 제거
spec:
  selector:
    app: report-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30015
  type: NodePort
