apiVersion: v1
kind: Service
metadata:
  name: search-service  # 이상한 문자 제거
spec:
  selector:
    app: search-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30011
  type: NodePort
