apiVersion: v1
kind: Service
metadata:
  name: auth-service  # 이상한 문자 제거
spec:
  selector:
    app: auth-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30002
  type: NodePort
