apiVersion: argoproj.io/v1alpha1  # Rollouts를 사용하기 위한 API 버전
kind: Rollout  # Rollout 리소스로 변경
metadata:
  name: webrtc-canary-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc-canary
  template:
    metadata:
      labels:
        app: webrtc-canary
    spec:
      containers:
      - name: canary-rollouts-webrtc
        image: gcu-bootstrap-dev.kr-central-2.kcr.dev/moldev-repository/bootstrap-webrtc:8
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: kc-backend-cr
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {}
      - setWeight: 50
      - pause: {}
      - setWeight: 75
      - pause: {}
      - setWeight: 100
