apiVersion: v1
kind: Service
metadata:
  name: webrtc-service  # 이상한 문자 제거
spec:
  selector:
    app: webrtc-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30115
  type: NodePort
