apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-composer-rollout
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: api-composer
  template:
    metadata:
      labels:
        app: api-composer
    spec:
      containers:
      - name: canary-rollouts-api-composer
        image: ziiyouth/bootstrap-api-composer:16
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_URL
          value: ""
        - name: SECRET_TOKEN
          value: ""
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {}
