apiVersion: v1
kind: Service
metadata:
  name: post-service  # 이상한 문자 제거
spec:
  selector:
    app: post-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001
  type: NodePort
