apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-canary-rollout
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx-canary
  template:
    metadata:
      labels:
        app: nginx-canary
    spec:
      containers:
        - name: nginx-canary
          image: ziiyouth/bootstrap-nginx:3
      strategy:
        canary:
          maxSurge: "25%"
          maxUnavailable: 0
          steps:
            - setWeight: 25
            - pause: {}
