apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: signaling-canary-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signaling-canary
  template:
    metadata:
      labels:
        app: signaling-canary
    spec:
      containers:
      - name: canary-rollouts-signaling
        image: gcu-bootstrap-dev.kr-central-2.kcr.dev/moldev-repository/bootstrap-signaling:56
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_URL
          value: ""
        - name: SECRET_TOKEN
          value: ""
      imagePullSecrets:
        - name: kc-backend-cr
        
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {}
      - setWeight: 50
      - pause: {}
      - setWeight: 75
      - pause: {}
      - setWeight: 100
