apiVersion: argoproj.io/v1alpha1  # Rollouts를 사용하기 위한 API 버전
kind: Rollout  # Rollout 리소스로 변경
metadata:
  name: signaling-canary-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: signaling-canary
  template:
    metadata:
      labels:
        app: signaling-canary
    spec:
      containers:
      - name: canary-rollouts-signaling
        image: gcu-bootstrap-dev.kr-central-2.kcr.dev/moldev-repository/bootstrap-signaling:0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {}
