apiVersion: v1
kind: Service
metadata:
  name: signaling-service
spec:
  selector:
    app: signaling-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30010
  - protocol: UDP
    port: 12345
    targetPort: 12345
    nodePort: 30033
  type: NodePort
