apiVersion: v1
kind: Service
metadata:
  name: signaling-service  # 이상한 문자 제거
spec:
  selector:
    app: signaling-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30010
  type: NodePort
