apiVersion: v1
kind: Service
metadata:
  name: signaling-service
spec:
  selector:
    app: signaling-canary
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30010
  - name: stun-turn
    protocol: UDP
    port: 3478
    targetPort: 8080
    nodePort: 30111
  type: NodePort
