apiVersion: v1
kind: Service
metadata:
  name: member-service  # 이상한 문자 제거
spec:
  selector:
    app: member-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30009
  type: NodePort
