apiVersion: argoproj.io/v1alpha1  # Rollouts를 사용하기 위한 API 버전
kind: Rollout  # Rollout 리소스로 변경
metadata:
  name: chatbot-canary-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-canary
  template:
    metadata:
      labels:
        app: chatbot-canary
    spec:
      containers:
      - name: canary-rollouts-chatbot
        image: gcu-bootstrap-dev.kr-central-2.kcr.dev/moldev-repository/bootstrap-chatbot:47
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_URL
          value: ""
        - name: SECRET_TOKEN
          value: ""
      imagePullSecrets:
        - name: kc-backend-cr
        
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {}
      - setWeight: 50
      - pause: {}
      - setWeight: 75
      - pause: {}
      - setWeight: 100
