apiVersion: v1
kind: Service
metadata:
  name: chatbot-service  # 이상한 문자 제거
spec:
  selector:
    app: chatbot-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30004
  type: NodePort
