apiVersion: v1
kind: Service
metadata:
  name: reply-service 
spec:
  selector:
    app: reply-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30003
  type: NodePort
